language: python

python:
  - "2.7"

install:
  - pip install -r requirements.txt
  - pip install 'kazoo <= 2.0' .
  - pip install coveralls

before_script:
  - sudo apt-get install zookeeperd

script: python setup.py test

after_success:
  - coveralls
