language: python

python:
  - "2.7"

install:
  - pip install 'kazoo <= 2.0'
  - pip install coveralls

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y zookeeperd

script: coverage run --source=zoosync setup.py test

after_success:
  - coveralls
